"""Deterministic worker execution and result-processing boundaries."""

from .circuit_breaker import (
    FamilyCircuitBreakerDependencies,
    FamilyCircuitBreakerRequest,
    FamilyCircuitBreakerResult,
    evaluate_family_circuit_breakers,
    family_circuit_broken,
)
from .dispatch import (
    DispatchCandidate,
    DispatchOutcome,
    DispatchQueueDependencies,
    MAX_DISPATCH_RETRIES,
    PermanentDispatchSkip,
    dispatch_pending_to_free_slots,
)
from .progress_checkpoint import (
    CONTROLLER_CHECKPOINT_FILE,
    ProgressCheckpointDependencies,
    ProgressCheckpointRequest,
    ProgressCheckpointResult,
    build_cheap_checkpoint_evidence,
    read_controller_checkpoint,
    refresh_progress_checkpoint,
    resolve_charged_gpu_count,
    write_controller_checkpoint,
)
from .result_processing import (
    OutputParser,
    OutputParserRegistry,
    ProcessedWorkerOutput,
    WorkerOutputRequest,
    create_synthetic_result_record,
    process_worker_output,
    synthetic_result_exit_status,
)
from .score_conversion_scheduling import (
    ScoreConversionSchedule,
    ScoreConversionSchedulingRequest,
    build_score_conversion_schedule,
    canonical_strict_metrics_present,
    deduplicate_scored_parent_results,
    is_canonical_score_conversion_result,
    result_requires_score_conversion,
    results_require_score_conversion,
    score_conversion_candidate_limit,
    score_conversion_parent_identity,
    select_score_conversion_parents,
)
from .worker_supervision import (
    WorkerDrainReport,
    WorkerSupervisionDependencies,
    WorkerSupervisionReport,
    drain_worker_slots,
    supervise_worker_slots,
)

__all__ = [
    "CONTROLLER_CHECKPOINT_FILE",
    "DispatchCandidate",
    "DispatchOutcome",
    "DispatchQueueDependencies",
    "MAX_DISPATCH_RETRIES",
    "FamilyCircuitBreakerDependencies",
    "FamilyCircuitBreakerRequest",
    "FamilyCircuitBreakerResult",
    "OutputParser",
    "OutputParserRegistry",
    "ProcessedWorkerOutput",
    "PermanentDispatchSkip",
    "ProgressCheckpointDependencies",
    "ProgressCheckpointRequest",
    "ProgressCheckpointResult",
    "ScoreConversionSchedule",
    "ScoreConversionSchedulingRequest",
    "WorkerOutputRequest",
    "WorkerDrainReport",
    "WorkerSupervisionDependencies",
    "WorkerSupervisionReport",
    "build_score_conversion_schedule",
    "build_cheap_checkpoint_evidence",
    "canonical_strict_metrics_present",
    "create_synthetic_result_record",
    "deduplicate_scored_parent_results",
    "dispatch_pending_to_free_slots",
    "drain_worker_slots",
    "evaluate_family_circuit_breakers",
    "family_circuit_broken",
    "is_canonical_score_conversion_result",
    "process_worker_output",
    "read_controller_checkpoint",
    "refresh_progress_checkpoint",
    "resolve_charged_gpu_count",
    "result_requires_score_conversion",
    "results_require_score_conversion",
    "score_conversion_candidate_limit",
    "score_conversion_parent_identity",
    "select_score_conversion_parents",
    "synthetic_result_exit_status",
    "supervise_worker_slots",
    "write_controller_checkpoint",
]
